#!/bin/sh
#
# Global post-merge hook. Only delegates; there is no global post-merge concern.
# See _lefthook-delegate for why hand-written hooks live here.

set -eu

exec "$(dirname "$0")/_lefthook-delegate" post-merge "$@"
